# Generated by Django 5.1.1 on 2024-10-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profiles',
            name='is_service_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profiles',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
