# Generated by Django 5.1.1 on 2024-10-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profiles_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
