# Generated by Django 5.1.1 on 2024-10-31 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_accountsecurity_bookinghistory_and_more'),
        ('services', '0006_alter_serviceprovider_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='service_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_name', to='services.service'),
        ),
    ]
