# Generated by Django 5.1.1 on 2024-10-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicecategory_options_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='categoryImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/category_images/'),
        ),
    ]
