# Generated by Django 5.1.1 on 2024-10-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_price_servicecategory_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='topServiceProvider',
            field=models.BooleanField(default=True),
        ),
    ]
