# Generated by Django 5.1.1 on 2024-10-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceprovider_topserviceprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
